### ISSUE TITLE
i would like to help adding some recipes 

### ISSUE THREAD

**Issue by yesn0t** [spacegoat3/ConfigurableRecipes#2]
hello ! i've been looking for a mod like this with on/off switches for the extra recipes, i've skimmed through the code and would like to send PRs for individual recipes, mainly a replacement tag for stone types, crafting cobwebs and deadbushes, but also some uncrafting recipes that normally require placing and breaking blocks such as clay, snowballs, ...

this issue is to ask for greenlight and possible advice before i get started x)
thanks and happy new year

**Comment by spacegoat3** [comment]
Of course, that would be great! But exactly what kind of advice you are looking for? I will try to help you as much as possible. 

Have a nice day and a happy new year!

**Comment by yesn0t** [comment]
good to hear , i started with something simple and tried to stay as close to the existing code as possible, being a new contributor to this repo there might be things i missed , let me know what you think :) 
for possible advice it was overthinking unimportant details such as commit messages and whether to modify single files per commits ^^'
in any case i appreciate the feedback

**Comment by spacegoat3** [comment]
Thank you so much, you did everything perfectly. But I would just like to know if we can talk on another platform other than GitHub?

For the advices,

1 - Commit messages are not so important, at least not for me. I always just write "Added files" :D
2 - You can modify or create as many as files you want for a single commit.

Again, thank you so much for your help and I just wanted to let you know that I am going to add you to the credits, if you don't want me to, just let me know.

Have a nice day and a happy new year!

**Comment by yesn0t** [comment]
i'm on discord at https://discordapp.com/users/903159675934097498

took me a while to find how to make a link to my DMs , would be easier if we shared a server x) 
are you on any mc modders server i could join ?

**Comment by spacegoat3** [comment]
Thank you so much. I am joined to CurseForge, The Fabric Project, and The Quilt Community Servers on the Discord.

**Comment by yesn0t** [comment]
oh okay, i'm `yesn_t#5296` , does this work ?

**Comment by spacegoat3** [comment]
Yes, I sent you a friend request. You can accept it by going to "Home" and then "Pending"
