### ISSUE TITLE
1.1.0 bug

### ISSUE THREAD

**Issue by nagongze** [spacegoat3/ConfigurableRecipes#6]
Version 1.1.0 has a bug?
I get both Torch and SoulTorch in Campfire, but I can't get any Torch in SoulCampfire.

**Comment by spacegoat3** [comment]
I am going to assume you are talking about the Campfire Torches Plus Mod? Because this is the page of a different mod.

Thank you for telling me though, I will fix it as soon as possible. Have a nice day :)
