### ISSUE TITLE
String Recipe?

### ISSUE THREAD

**Issue by ardissaps** [spacegoat3/ConfigurableRecipes#8]
Would you ad String recipe? thx

**Comment by spacegoat3** [comment]
I am not so sure. String is a material that comes from an entity, which is the Spider. It will be like adding a recipe for Milk. But thanks for the feedback though.

**Comment by ardissaps** [comment]
> I am not so sure. String is a material that comes from an entity, which is the Spider. It will be like adding a recipe for Milk. But thanks for the feedback though.

Irl string can be crafted with plant, or wool, it is hard to find sting if we first spawn in an area with no spiders/sheep around (to craft bed). Maybe you can add it can be achieved by wool to string?

**Comment by spacegoat3** [comment]
Hmm, I see. I will implement it when I have the time. Thanks for the idea :D

**Comment by ardissaps** [comment]
Thank you very much (1.18.2) :D
